Models/Permissao.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AutenticacaoEFCookie.Models
{
    public class Permissao
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int IdPermissao { get; set; }

        [Required]
        [StringLength(100,MinimumLength=2)]
        public string Nome { get; set; }
        public ICollection<UsuarioPermissao> UsuariosPermissoes { get; set; }
    }
}

Models/Usuario.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace AutenticacaoEFCookie.Models
{
    public class Usuario
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int IdUsuario { get; set; }

        [Required]
        [StringLength(100,MinimumLength=4)]
        public string Nome { get; set; }

        [Required]
        [StringLength(50,MinimumLength=4)]
        public string Email { get; set; }

        [Required]
        [StringLength(12, MinimumLength=4)]
        [DataType(DataType.Password)]
        public string Senha { get; set; }

        public ICollection<UsuarioPermissao> UsuariosPermissoes { get; set; }
        
    }
}

Models/UsuarioPermissao.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AutenticacaoEFCookie.Models
{
    public class UsuarioPermissao
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int IdUsuarioPermissao { get; set; }

        [Required]
        public int IdUsuario { get; set; }

        [Required]
        public int IdPermissao { get; set; }

        [ForeignKey("IdUsuario")]
        public Usuario Usuario { get; set; }

        [ForeignKey("IdPermissao")]
        public Permissao Permissao { get; set; }
    }
}

Controllers/ContaController.cs
using AutenticacaoEFCookie.Dados;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using AutenticacaoEFCookie.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using System.Collections.Generic;
using System.Security.Claims;
using Microsoft.EntityFrameworkCore;

namespace AutenticacaoEFCookie.Controllers
{
    public class ContaController : Controller
    {
        readonly AutenticacaoContext _contexto;

        public ContaController(AutenticacaoContext context){
            _contexto = context;
        }

        [HttpGet]
        public IActionResult Login(){
            return View();
        }

        [HttpPost]
        public IActionResult Login(Usuario usuario){
            try{
               

                Usuario user = _contexto.Usuarios.Include("UsuariosPermissoes").Include("UsuariosPermissoes.Permissao").FirstOrDefault(c => c.Email == usuario.Email && c.Senha == usuario.Senha);

                if(user != null){
                    var claims = new List<Claim>();
                    claims.Add(new Claim(ClaimTypes.Email, user.Email));
                    claims.Add(new Claim(ClaimTypes.Name, user.Nome));
                    claims.Add(new Claim(ClaimTypes.Sid, user.IdUsuario.ToString()));

                    foreach (var item in user.UsuariosPermissoes)
                    {
                        claims.Add(new Claim(ClaimTypes.Role, item.Permissao.Nome));
                    }

                    var claimsIdentity = new ClaimsIdentity(
                        claims, CookieAuthenticationDefaults.AuthenticationScheme
                    );

                    HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity));

                    return RedirectToAction("Index","Financeiro");
                }
                return View(usuario);
            }catch(System.Exception ex){
                return BadRequest(ex.Message);
            }
        }

        [HttpGet]
        public IActionResult Sair(){
            HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Login");
        }

    }
    
}

Controllers/FinanceiroController.cs
using AutenticacaoEFCookie.Dados;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using AutenticacaoEFCookie.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication.Cookies;
using System.Collections.Generic;
using System.Security.Claims;

namespace AutenticacaoEFCookie.Controllers
{
    [Authorize(Roles="Financeiro")]
    public class FinanceiroController : Controller
    {
        public IActionResult Index(){
            return View();
        }

    }
}

Views/Conta/Login.cshtml
@model AutenticacaoEFCookie.Models.Usuario

@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" href="~/css/login.css" />


<div class="container">
    <div class="row">
    	<div class="col-md-4 col-md-offset-4">
    		<div class="panel panel-default">
			  	<div class="panel-heading">
			    	<h3 class="panel-title">Login via site</h3>
			 	</div>
                 
                    <div class="panel-body">
                        <form asp-action="Login">
                        <fieldset>
                            <div class="form-group">
                                <input class="form-control" asp-for="Email"  placeholder="yourmail@example.com" name="email" type="text">
                            </div>
                            <div class="form-group">
                                <input class="form-control" asp-for="Senha"  placeholder="Password" name="Senha" type="password" value="">
                            </div>
                            <input class="btn btn-lg btn-success btn-block" type="submit" value="Login">
                        </fieldset>
                        </form>
                        <hr/>
                        
                    </div>
			    
            </div>
		</div>
	</div>
</div>

Views/Financeiro/Index.cshtml
<div class="row">
    <h3 class="center">
        Página Autenticada Financeiro
    </h3>
</div>

Views/RecursosHumanos/Index.cshtml
<div class="row">
    <h3 class="center">
        Página Autenticada Recursos Humanos
    </h3>
</div>

Views/Shared/_Layout.cshtml
@using System.Security.Claims;

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Autenticação</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Autenticacao EF Cookie</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @{  
                        if(User.Identity.IsAuthenticated)
                        { 
                            if(User.IsInRole("Financeiro")){  
                                <li><a asp-area="" asp-controller="Financeiro" asp-action="Index">Financeiro</a></li>
                            }

                            if(User.IsInRole("Recursos Humanos")){  
                                <li><a asp-area="" asp-controller="RecursosHumanos" asp-action="Index">Recursos Humanos</a></li>
                            }
                        }
                    }
                </ul>
                @{
                    if(User.Identity.IsAuthenticated)
                    {
                        <ul class="nav navbar-nav navbar-right">
                            <li><a href="#">@User.Identity.Name</a></li>
                            <li><a href="#">@User.Claims.Where(c => c.Type == ClaimTypes.Email).Select(c => c.Value).SingleOrDefault()</a></li>                            
                            <li><a asp-area="" asp-controller="Conta" asp-action="Sair">Sair</a></li>
                        </ul>
                    }
                }
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Autenticacao EF Cookie</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>